const OPENROUTER_API_KEY = import.meta.env.VITE_OPENROUTER_API_KEY || "";

export async function callOpenRouter(messages: any[], model: string = "openai/gpt-4o") {
  const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      "Authorization": `Bearer ${OPENROUTER_API_KEY}`,
      "Content-Type": "application/json",
      "HTTP-Referer": window.location.origin,
      "X-Title": "AdStudio Pro",
    },
    body: JSON.stringify({ model, messages }),
  });
  
  if (!response.ok) {
    throw new Error("Failed to call OpenRouter");
  }
  
  const data = await response.json();
  return data.choices[0].message.content;
}

export async function generateEbookContent(topic: string, type: 'title' | 'outline' | 'script') {
  const prompts = {
    title: `Create a catchy title for an ebook about: ${topic}. Return only the title, nothing else.`,
    outline: `Create a detailed outline with chapters for an ebook about: ${topic}. Format as a numbered list.`,
    script: `Write the full content for an ebook about: ${topic}. Include introduction, chapters, and conclusion.`
  };
  
  return await callOpenRouter([{ role: 'user', content: prompts[type] }]);
}

export async function evaluateEbookContent(ebook: { title: string, outline: string, script: string }) {
  const prompt = `Evaluate the following ebook generated by an AI agent. Provide feedback and a score from 0 to 10 based on quality, coherence, and creativity.
  
  Title: ${ebook.title}
  Outline: ${ebook.outline}
  Script: ${ebook.script}
  
  Format the response as JSON: { "feedback": "...", "score": number }`;
  
  const response = await callOpenRouter([{ role: 'user', content: prompt }]);
  return JSON.parse(response);
}
