export async function callOpenRouter(messages: any[], model: string = "openai/gpt-4o") {
  const response = await fetch("/api/openrouter", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ messages, model }),
  });
  
  if (!response.ok) {
    throw new Error("Failed to call OpenRouter");
  }
  
  const data = await response.json();
  return data.choices[0].message.content;
}

export async function generateEbookContent(topic: string, type: 'title' | 'outline' | 'script') {
  const prompts = {
    title: `Create a catchy title for an ebook about: ${topic}`,
    outline: `Create a detailed outline for an ebook about: ${topic}`,
    script: `Write the full content for an ebook about: ${topic}`
  };
  
  return await callOpenRouter([{ role: 'user', content: prompts[type] }]);
}

export async function evaluateEbookContent(ebook: { title: string, outline: string, script: string }) {
  const prompt = `Evaluate the following ebook generated by an AI agent. Provide feedback and a score from 0 to 10 based on quality, coherence, and creativity.
  
  Title: ${ebook.title}
  Outline: ${ebook.outline}
  Script: ${ebook.script}
  
  Format the response as JSON: { "feedback": "...", "score": number }`;
  
  const response = await callOpenRouter([{ role: 'user', content: prompt }]);
  return JSON.parse(response);
}
